### ISSUE TITLE
[common] 앱 디자인 초안 작성하기

### ISSUE THREAD

**Issue by Junhyeon2** [9trees/youngest-common#1]
# 디자인 초안 작성
- 댓글로 각자 한개 이상 화면 맡아서 작성
- 선착순이고, 맨 마지막은 남은 화면 모두 작성
- 양식은 자유 형식

## 사용자 화면
- 작성자: ~복다훈~, ~정주성~, ~서정한~, ~허빛찬샘~, ~김준현~

### 화면
- ~로그인: 소셜 연동~(복다훈)
- ~회원가입~(허빛찬샘)
- ~호출 화면: 지도,필터,호출 버튼~(김준현)
- ~호출 중: 선택~(정주성)
- ~호출 실패~(서정한)
- ~히스토리: 목록 및 개인 설정~(복다훈)

## 점주 화면
- 작성자: ~권준범~, ~허재혁~, ~박철홍~, ~황남기~

### 화면
- ~로그인: 어드민으로 가입~(권준범)
- ~호출 대기~(김준현)
- ~호출된 목록: 선택, 거절~(박철홍)
- ~호출 중~(황남기)
- ~히스토리: 목록 및 개인 설정~(허재혁)

**Comment by kwonjunbeom** [comment]
권준범 - 로그인: 어드민으로 가입
개꿀~?

**Comment by BicchansamHeo** [comment]
회원가입

**Comment by jungjusung** [comment]
호출 중

**Comment by hwangnk** [comment]
점주화면 호출 중

**Comment by BokDaHoon** [comment]
복다훈 - 로그인, 히스토리
개꿀~?

**Comment by Junhyeon2** [comment]
사용자 호출화면

**Comment by life0style0** [comment]
점주 히스토리

**Comment by chro1** [comment]
박철홍 - 호출된 목록: 선택, 거절

**Comment by SeoJeongHan** [comment]
서정한 : 사용자 - 호출실패
